### ISSUE TITLE
jacobian error?

### ISSUE THREAD

**Issue by Roger-Chuh** [SubMishMar/camera_imu_calibration#1]
hi, thanks for open sourcing your work.
i am confused about the line below, the jacobians of line 241 and line 245 are the same, is this some kind of bug? appreciate your reply, again than you very much.
https://github.com/unmannedlab/camera_imu_calibration/blob/4c90aea2438a9b298f0d1ca5826b6a5fe817d5e0/src/update/UpdaterCameraTracking.cpp#L241

**Comment by SubMishMar** [comment]
Yes. My derivation says so. I do not have the derivation steps with me right now, but I checked my notes where I had written the final equations and they are the same.
![Screenshot from 2022-07-22 11-32-19](https://user-images.githubusercontent.com/28704031/180483949-66aeff6b-c95d-4876-b256-e0f4f2fd73b7.png)

**Comment by Roger-Chuh** [comment]
thank you for your immediate reply, i did the derivations and your jacobians are indeed corret,
